export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';


export const LOADING_PRODUCT = 'LOADING_PRODUCT'
export const RETRIEVE_PRODUCT = 'RETRIEVE_PRODUCT'
export const INSERTED_PRODUCT = 'INSERTED_PRODUCT'
export const GET_PRODUCT = 'GET_PRODUCT'
export const INSERT_PRODUCT = 'INSERT_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATED_PRODUCT = 'UPDATED_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETED_PRODUCT = 'DELETED_PRODUCT'
export const ERROR_PRODUCT = 'ERROR_PRODUCT'


export const USER_SIGUP = 'USER_SIGUP';
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"
export const AUTH_ERROR = "AUTH_ERROR"
export const USER_EMAIL = "USER_EMAIL";
export const SIGNOUT_USER = "SIGNOUT_USER";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const OTP = "OTP"
export const LOADING_AUTH = "LOADING_AUTH"
export const USER_DATA = "USER_DATA"

//